services:
  - type: worker
    name: english-cards-bot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ALLOWED_USER_ID
        value: "1152370552"
